[package]
name = "lockbox"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.4", features = ["wgpu", "image"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"